# Generated by Django 2.2.8 on 2020-07-07 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Altermarché', 'Altermarché'), ('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Jardi', 'Jardi per tots'), ('Chantier', 'Chantier participatif'), ('Documentation', 'Documentation'), ('Ecovillage', 'Ecovillage'), ('Point', 'Point de vue'), ('KitPerma', 'Kit Perma Ecole'), ('Recette', 'Recette'), ('Jardin', 'Jardins partagés'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('estPublic', models.BooleanField(default=False, verbose_name='Public ou réservé aux membres collectifshl')),
                ('estModifiable', models.BooleanField(default=False, verbose_name="Modifiable par n'importe qui")),
                ('date_dernierMessage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du dernier message')),
                ('dernierMessage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('estArchive', models.BooleanField(default=False, verbose_name="Archiver l'article")),
                ('start_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, affichage dans l'agenda)")),
                ('end_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)")),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name="Titre de l'événement (si laissé vide, ce sera le titre de l'article)")),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='jj/mm/année', verbose_name='Date')),
                ('end_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name='Date de fin (optionnel pour un evenement sur plusieurs jours)')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Part', 'Participation à un évènement'), ('AGO', "Organisation d'une AGO"), ('Projlong', 'Projet a long terme'), ('Projcourt', 'Projet a court terme'), ('Projponct', 'Projet ponctuel')], default='Part', max_length=10, verbose_name='categorie')),
                ('statut', models.CharField(choices=[('prop', 'Proposition de projet'), ('AGO', "Fiche projet soumise à l'AGO"), ('vote', 'Soumis au vote'), ('accep', "Accepté par l'association"), ('refus', "Refusé par l'association")], default='prop', max_length=5, verbose_name='statut')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('estPublic', models.BooleanField(default=False, verbose_name='Public (cochez) ou Interne (décochez) [réservé aux membres collectifshl]')),
                ('coresponsable', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Référent du projet')),
                ('lien_vote', models.URLField(blank=True, null=True, verbose_name='Lien vers le vote (balotilo.org)')),
                ('lien_document', models.URLField(blank=True, default='', null=True, verbose_name='Lien vers un document explicatif (en ligne)')),
                ('fichier_projet', models.FileField(blank=True, default=None, null=True, upload_to='projets/%Y/%m/')),
                ('date_fichier', models.DateTimeField(auto_now=True)),
                ('date_dernierMessage', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('dernierMessage', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, pour affichage dans l'agenda)")),
                ('end_time', models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)")),
                ('estArchive', models.BooleanField(default=False, verbose_name='Archiver le projet')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
    ]
