# Generated by Django 2.2.13 on 2020-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200707_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('1', 'Annonce'), ('2', 'Administratif'), ('3', 'Agenda'), ('4', 'Chantier participatif'), ('6', 'Altermarché'), ('5', 'Ressources'), ('0', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
