# Generated by Django 2.2.8 on 2020-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcheLibre', '0016_auto_20200707_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='statut_adhesion',
            field=models.IntegerField(choices=[('', '-----------'), (0, 'Je souhaite devenir membre du collectif  et utiliser le site'), (1, 'Je souhaite utiliser le site, mais ne pas devenir membre du collectif des Collectifs Hameaux Legers'), (2, 'Je suis déjà membre du Collectif')], default='0'),
        ),
    ]
