# Generated by Django 2.2.8 on 2020-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcheLibre', '0017_auto_20200707_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='statut_adhesion_rtg',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre du collectif 'Ramene Ta Graine' et utiliser le site"), (1, 'Je souhaite utiliser le site, mais ne pas devenir membre du collectif RTG'), (2, 'Je suis déjà membre du collectif Ramene Ta Graine')], default='0'),
        ),
    ]
