# Generated by Django 2.2.8 on 2020-07-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcheLibre', '0018_auto_20200708_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='statut_adhesion_rtg',
        ),
        migrations.DeleteModel(
            name='MessageGeneralRTG',
        ),
    ]
